# Maldición de dimensionalidad y polynomial features

Nancy Patricia Girón Muñoz

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

## 1 Variable

In [2]:
x = np.random.rand(5,1)
x

array([[0.9082766 ],
       [0.64105941],
       [0.14120948],
       [0.9661319 ],
       [0.06680915]])

In [3]:
poly = PolynomialFeatures(3)
poly.fit_transform(x)

array([[1.00000000e+00, 9.08276599e-01, 8.24966380e-01, 7.49297658e-01],
       [1.00000000e+00, 6.41059409e-01, 4.10957166e-01, 2.63447958e-01],
       [1.00000000e+00, 1.41209476e-01, 1.99401161e-02, 2.81573334e-03],
       [1.00000000e+00, 9.66131904e-01, 9.33410855e-01, 9.01798006e-01],
       [1.00000000e+00, 6.68091516e-02, 4.46346273e-03, 2.98200158e-04]])

## 2 Variables

In [4]:
x1 = np.random.rand(5,2)
x1

array([[0.65291912, 0.50367968],
       [0.50085083, 0.32128426],
       [0.23449103, 0.71830793],
       [0.25276477, 0.06981957],
       [0.52637757, 0.4789086 ]])

In [5]:
poly1 = PolynomialFeatures(3)
poly1.fit_transform(x1)

array([[1.00000000e+00, 6.52919116e-01, 5.03679679e-01, 4.26303372e-01,
        3.28862091e-01, 2.53693219e-01, 2.78341620e-01, 2.14720345e-01,
        1.65641152e-01, 1.27780119e-01],
       [1.00000000e+00, 5.00850832e-01, 3.21284260e-01, 2.50851556e-01,
        1.60915489e-01, 1.03223576e-01, 1.25639211e-01, 8.05946565e-02,
        5.16996137e-02, 3.31641101e-02],
       [1.00000000e+00, 2.34491031e-01, 7.18307931e-01, 5.49860437e-02,
        1.68436767e-01, 5.15966284e-01, 1.28937341e-02, 3.94969113e-02,
        1.20989466e-01, 3.70622674e-01],
       [1.00000000e+00, 2.52764765e-01, 6.98195683e-02, 6.38900266e-02,
        1.76479268e-02, 4.87477212e-03, 1.61491476e-02, 4.46077408e-03,
        1.23217063e-03, 3.40354485e-04],
       [1.00000000e+00, 5.26377574e-01, 4.78908599e-01, 2.77073351e-01,
        2.52086747e-01, 2.29353446e-01, 1.45845198e-01, 1.32692810e-01,
        1.20726511e-01, 1.09839338e-01]])

## 3 Variables

In [6]:
x2 = np.random.rand(5,3)
x2

array([[0.28702125, 0.3769296 , 0.37469468],
       [0.80628723, 0.64409748, 0.05538766],
       [0.2236088 , 0.01754805, 0.84870739],
       [0.34731166, 0.84351229, 0.68190993],
       [0.49581436, 0.19166853, 0.06081481]])

In [7]:
poly2 = PolynomialFeatures(3)
poly2.fit_transform(x1)

array([[1.00000000e+00, 6.52919116e-01, 5.03679679e-01, 4.26303372e-01,
        3.28862091e-01, 2.53693219e-01, 2.78341620e-01, 2.14720345e-01,
        1.65641152e-01, 1.27780119e-01],
       [1.00000000e+00, 5.00850832e-01, 3.21284260e-01, 2.50851556e-01,
        1.60915489e-01, 1.03223576e-01, 1.25639211e-01, 8.05946565e-02,
        5.16996137e-02, 3.31641101e-02],
       [1.00000000e+00, 2.34491031e-01, 7.18307931e-01, 5.49860437e-02,
        1.68436767e-01, 5.15966284e-01, 1.28937341e-02, 3.94969113e-02,
        1.20989466e-01, 3.70622674e-01],
       [1.00000000e+00, 2.52764765e-01, 6.98195683e-02, 6.38900266e-02,
        1.76479268e-02, 4.87477212e-03, 1.61491476e-02, 4.46077408e-03,
        1.23217063e-03, 3.40354485e-04],
       [1.00000000e+00, 5.26377574e-01, 4.78908599e-01, 2.77073351e-01,
        2.52086747e-01, 2.29353446e-01, 1.45845198e-01, 1.32692810e-01,
        1.20726511e-01, 1.09839338e-01]])

## Conclusiones

Se puede observar que cuando se tienen mas variables, se pueden generar mayor cantidad de combinaciones de Features. 