# Operaciones Lógicas 

Nancy Patricia Girón Muñoz

In [61]:
import numpy as np

In [62]:
def activation(m):
    return (m>=0).astype(np.float)

def Operacion(x, weights):
    return np.matmul(x, weights)

In [64]:
x = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])

## AND

In [65]:
weights = np.array([10, 10, -15.])
prediction = activation(Operacion(np.column_stack((x, np.ones(x.shape[0]))), weights)).reshape(-1, 1)

print("Operacion AND")
print("Entrada")
print(str(x))
print("Salida")
print(str(prediction))

Operacion AND
Entrada
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Salida
[[0.]
 [0.]
 [0.]
 [1.]]


## OR

In [66]:
weights = np.array([30., 30., -1.])
prediction = activation(Operacion(np.column_stack((x, np.ones(x.shape[0]))), weights)).reshape(-1, 1)

print("Operacion OR")
print("Entrada")
print(str(x))
print("Salida")
print(str(prediction))

Operacion OR
Entrada
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Salida
[[0.]
 [1.]
 [1.]
 [1.]]


## NOT

In [67]:
x = np.array([0, 1]).reshape(-1, 1)
x

array([[0],
       [1]])

In [70]:
weights = np.array([-10., 1])
prediction = activation(Operacion(np.column_stack((x, np.ones(x.shape[0]))), weights)).reshape(-1, 1)

print("Operacion NOT")
print("Entrada")
print(str(x))
print("Salida")
print(str(prediction))

Operacion NOT
Entrada
[[0]
 [1]]
Salida
[[1.]
 [0.]]
